version: "2"
services:

#   Jaeger
#  jaeger-aio:
#    image: jaegertracing/all-in-one:latest
#    container_name: otel-jaeger
#    restart: unless-stopped
#    ports:
#      - "16686:16686"
#      - "14268"
#      - "14250"

  # Zipkin
  zipkin-aio:
    image: openzipkin/zipkin:latest
    container_name: otel-zipkin
    restart: unless-stopped
    environment:
      - JAVA_OPTS=-Xms1024m -Xmx1024m -XX:+ExitOnOutOfMemoryError
    ports:
      - "9411:9411"

  # Collector
  collector:
    image: ${OTELCOL_IMG}
    container_name: otel-collector
    restart: unless-stopped
    command: ["--config=/etc/otel-collector-config.yaml", "${OTELCOL_ARGS}"]
    volumes:
      - ./otel-collector-config.yaml:/etc/otel-collector-config.yaml
      - ./test-logs:/etc/test-logs:rw
    ports:
      - "1888:1888"   # pprof extension
      - "8888:8888"   # Prometheus metrics exposed by the collector
      - "8889:8889"   # Prometheus exporter metrics
      - "13133:13133" # health_check extension
      - "4317:4317"   # OTLP gRPC receiver
      - "4318:4318"   # OTLP HTTP receiver
      - "55679:55679" # zpages extension
    depends_on:
#      - jaeger-aio
      - zipkin-aio

  prometheus:
    container_name: otel-prometheus
    image: prom/prometheus:latest
    restart: unless-stopped
    volumes:
      - ./prometheus.yaml:/etc/prometheus/prometheus.yml
    ports:
      - "9090:9090"
